dist: xenial
language: python
python:
  - "3.5"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=controller --cov-report term test/
after_success:
  - codecov
