dist: xenial
language: python
python:
  - "3.5"
  - "3.7"
cache: pip
before_install:
  - sudo apt-get install -y mosquitto
install:
  - pip install -r requirements.txt
script:
  - flake8 --max-line-length=120 *.py controller/
  - pytest --cov=controller --cov-report term test/
  - python poupool.py --fake-devices --test-start
after_success:
  - codecov
